name: getx_fire
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com
repository: https://github.com/jonasreycian/getx_fire

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cloud_firestore:
  crypto: ^3.0.2
  firebase_analytics: ^10.1.4
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_crashlytics: ^3.0.15
  firebase_dynamic_links: ^5.0.15
  firebase_in_app_messaging: ^0.7.0+14
  firebase_storage:
  freezed_annotation: ^2.2.0
  get: ^4.6.5
  get_storage: ^2.0.3
  google_sign_in: ^6.0.1
  json_annotation: ^4.8.0
  path: ^1.8.0
  sign_in_with_apple: ^4.3.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lints: ^2.0.0
  flutter_test:
    sdk: flutter
